### ISSUE TITLE
ImportError: No module named _udt

### ISSUE THREAD

**Issue by bodenr** [lilydjwg/udt_py#1]
I'm just getting started with UDT and python ctypes in general, but when I try to run any of the sample py files I get the following:

Traceback (most recent call last):
  File "/home/boden/workspaces/dtls/udt_py/test_server.py", line 3, in <module>
    import udt
  File "/home/boden/workspaces/dtls/udt_py/udt.py", line 3, in <module>
    from _udt import *
ImportError: No module named _udt

I've verified ctypes is working with a very simple test.

Any tips appreciated.

**Comment by lilydjwg** [comment]
I think you are using Python 2 with those files, but this is a Python 3 branch which I don't expect to work with Python 2.

Those test scripts aren't converted to Python 3 yet. I'll try to do it when I have time.

**Comment by lilydjwg** [comment]
Most of them work in Python 3 now.
